# -*- coding: utf-8 -*-
"""Chapter 4 - Workflow: Code Style.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILZJDQx71sV3nn3gV_D5qu3cht7GtDbM

# Chapter 4 - Workflow: Code Style

Este capítulo presentará los puntos más importantes de la guía de estilo tidyverse, que se utiliza a lo largo de este libro.

Estilizar el código te parecerá tedioso al principio, pero si lo practicas, pronto se convertirá en algo natural
"""

install.packages('nycflights13')

library(tidyverse)
library(nycflights13)

"""## Nombres"""

# Los nombres de las variables (las creadas por <- y mutate()) deben utilizar sólo letras minúsculas, números y _. Utiliza _ para separar las palabras dentro de un nombre.

# Strive for:
short_flights <- flights |> filter(air_time < 60)

# Avoid
SHORTFLIGHTS <- flights |> filter(air_time < 60)

# Como regla general, es mejor preferir nombres largos y descriptivos que sean fáciles de entender que nombres concisos que sean rápidos de escribir. Los nombres cortos ahorran relativamente poco tiempo al escribir código, pero pueden consumir mucho tiempo cuando vuelvas a un código antiguo y te veas obligado a descibrar una abreviatura críptica.

"""## Espacios"""

# Pon espacios a ambos lados de los operadores amtemáticos aparte de ^ (es decir, +, -, , ==, <, ...) y arededor del operadore de asignación

# Strive for
z <- (a + b)^2 / d

# Avoid
z<-( a + b ) ^ 2/d

# No pongas espacios dentro o fuera de los paréntesis en las lamadas a funciones normales. Pon siempre un espacio despues de una coma, como en el ingles estándar.

# Strive for
mean(x, na.rm = TRUE)

# Avoid
mean (x ,na.rm=TRUE)

# Está bien añadir espacios extra si mejora la alineación. Por ejemplo, si estás creadndo múltiples variables un mutate() puedes añadir espacios para que todas las = queden alineadas. Así será más fácil hojear el código.

flights |>
  mutate(
    speed       = distance / air_time,
    dep_hour    = dep_time %/% 100,
    dep_minute  = dep_time %% 100
  )
# Cómo dep_time estpa en formato HMM, utilizamos la dicisión entera (%/%) para obtener la hora y el resto(%%) para obtener el minuto.

"""## Tuberías |>"""

# |> siempre debe ir precesido de un espacio y, por lo general, debe ser el último elemento de la línea. Esto facilita añadir nuevos pasos, reorganizar pasos existentes, modificar elementos dentro de un paso y obtener una visión de 10.000 pies hojeando los verbos de la parte izquierda.
# Strive for
flights |>
  filter(lis.na(ar_delay), lis.na(tailnum)) |>
    count(dest)

# Avoid
flights|>filter(lis.na(ar_delay), lis.na(tailnum))|>count(dest)

# SI la función que estás canalizando tiene argumentos con nombre (como mutate() o sumarize()), coloca cada argumento en un línea nueva. Si la función no tiene argumentos con nombre (como select() o filter()), mantenlo todo en una linea a menos que quepa, en cuyo caso debes poner cada argumento en su propia linea.
# Strive for
flights |>
  group_by(tailnum) |>
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )
# Avoid
flights |>
  group_by(
    tailnum
    ) |>
    summarize(delay = (arr_delay, na.rm = TRUE), n = n())

# Está bien eludir algunas de estas reglas si tu fragmento cabe fácilmente en una línea. Pero, según nuestra experiencia colectiva, es habitual que los fragmentos cortos se alarguen,  por lo que normalmente ahorrarás tiempo a largo palzo si empiezas con todo el espacio vertical que necesites:
# This fits compactly on one line
df |> mutate(y = x + 1)

# While this takes up 4x as many lines, it's easily extended to more variables and more steps in the future
df |>
  mutate(
  y = x + 1
  )

# Desconfía de escribir tuberías muy largas, digamos de mpas de 10-15 líneas. Intenta dividirlas en subtareas más pequeñas, dando a ada tarea un nombre informativo. Los nombres ayudarán al lector a saber qupe está ocurriendo y le facilitarpan la comprobación de que los resultados intemedios son los esperados

"""## ggplot2"""

# Las mismas reglas básicas que se aplican a la tubería también se aplican a ggplot2; sólo tienes que tratar + del mismo modo que |>
flights |>
  group_by(month) |>
  sumarize(
    delay = mean(arr_delay, na.rm = TRUE)
  ) |>
  ggplot(aes(x = month, y = delay)) +
  geom_point() +
  geom_line()
# Si no caben todos los argumentos de una función en una sola línea, pon cada argumento en su propia línea
flights |>
  group_by(dest) |>
  summarize(
    distance = mean(distance),
    speed = mean(distance / air_time, na.rm = TRUE)
  ) |>
  ggplot(aes(x = distance,y = speed)) +
  geom_smooth(
    method = 'loess',
    span = 0.5,
    se = FALSE,
    color = 'white',
    linewidth = 4
  ) +
  geom_point()

# Observa la transición de |> a +. Desearíamos que esta transición no fuera necesaria, pero por desgracia, ggplot2 se escribió antes de que se descubriera la tubería

"""## Ejercicios"""

#1. Modifica el estilo de las siguientes tuberías siguiendo las pautas anteriores.

flights |>
  filter(dest == 'IAH') |>
  group_by(year, month, day) |>
  summarize(
    n = n(),
    delay = mean(arr_delay, na.rm = TRUE)
  ) |>
  filter(n > 10)

flights |>
  filter(carrier == 'UA', dest %in% c('IAH', 'HOU'),
    sched_dep_time > 0900, sched_arr_time < 2000) |>
  group_by(flight) |>
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n = n()
  ) |>
  filter(n > 10)

